### ISSUE TITLE
request: allow for more configurations

### ISSUE THREAD

**Issue by vmarchaud** [similarweb/statusbay-helm#34]
Hi,

I'm deploying statusbay on GKE with the following setup:
 - one cluster used to host ui+api+database
 - one staging cluster that connect to the db
 - one prod cluster that connect to the db

Every cluster is using a different GCP account to i must expose the db to internet so i can monitor the deployments on all cluster (would better to use the api instead of the database in the future).

However i had some issues with the chart as it is today:
- API + UI services are `ClusterIP`, GKE only allow ingress to service that are `NodePort` or `LoadBalancer` so that would be helpful if configurable
- By default GKE Ingress use `/` to check if the service is working, it's working on the UI since it expose the frontend but the API is failing because of that. I believe you should add the `readinessProbe` and `livenessProbe` to both.
- I use `cert-manager` to get SSL cert for both the API/UI [with annonations on the ingress](https://cert-manager.io/docs/usage/ingress/), however i need to define the `tls` config. Should be perfect if you could add the options on the chart !

I've had other issue because of the database need to be exposed to internet but that's not really whats the chart is about. However you could rely on the official stable `mysql` chart to ease that part

Thanks for statusbay by the way, cool software !

**Comment by kaplanelad** [comment]
Hey, @vmarchaud I'm happy that you like our tool and using it :) 

To improve our chart, can you please share with us the values.yaml file configuration? I want to understand better what we need to add to improve the deployment flow.

**Comment by vmarchaud** [comment]
```
service:
  api:
    type: NodePort
  ui:
    type: NodePort
    annotations:
      "beta.cloud.google.com/backend-config": '{"default": "komiser-default-config"}'
ingress:
  api:
    host: ${local.statusbay_api_endpoint}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "${local.statusbay_api_endpoint}."
      "cert-manager.io/cluster-issuer": "ssl-cert-issuer"
    tls:
    - hosts:
      - ${local.statusbay_api_endpoint}
      secretName: statusbay-api-tls
  ui:
    host: ${local.statusbay_ui_endpoint}
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "${local.statusbay_ui_endpoint}."
      "cert-manager.io/cluster-issuer": "ssl-cert-issuer"
    tls:
    - hosts:
      - ${local.statusbay_ui_endpoint}
      secretName: statusbay-ui-tls
ui:
  replicas: 2
watcher:
  kubernetes:
    application:
      cluster_name: ${var.environment}
      slack:
        default_channels:
          - "#releases"
database:
  host: 172.16.0.1
  service:
    exposeToInternet: "true"
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "${local.statusbay_database_endpoint}."
```

Apparently i messed up and you actually allow configuring the service type so you can ignore 1).
